config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "projects#index"

  resources :projects, only: [:index, :new] do
    new do
      get 'contact'
      get 'aboutme'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def new
  end

  def contact
  end

  def aboutme
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{charset: "UTF-8"}/
    %title sho-ta portfolio
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
    %meta{content: "カメラマン　sho-ta　の作品紹介", name: "description"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %link{href: "images/android-chrome.png", rel: "icon", type: "image/png"}/

    / スライドcss,js
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}

    / リセットCSS
    %link{href: "https://unpkg.com/ress/dist/ress.min.css", rel: "stylesheet"}/
    -# %link{href: "https://fonts.google.apis.com/css?family=Philosopher", rel: "stylesheet"}/

  %body
    = yield

app/views/partial/_footer.html.haml
%footer
  .wrapper
    %p
      %small © 2019 sample

app/views/partial/_header.html.haml
%body
  %header.page-header.wrapper
    %h1
      = link_to root_path do
        = image_tag "", class: "logo"
        ここにlogoを配置
    %nav
      %ul.main-nav
        %li.btn-1
          = link_to aboutme_new_project_path do
            About Me
        %li.btn-6
          = link_to new_project_path do
            Photo diary
        %li.btn-1
          = link_to contact_new_project_path do
            Contact

app/views/projects/aboutme.html.haml
#introduction.big-bg
  = render "partial/header"
  .wrapper
    %h2.page-title About Me
.aboutme-contents.wrapper
  %article
    %header.post-info
      %h2.post-title 自己紹介
      %p.post-date
        5/20
        %span 2019
      %p.post-cat My introduction
    = image_tag "/assets/IMG_9219.JPG"
    %p
      関西出身。2019年生まれ、カメラマン。
      半年間のカナダ留学を経て
      広告、人物、風景、を中心に活動しております。
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
    %p
      Englishーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
      ーーーーーーーーーーーーーーーーーーーーーーーーーーー
    %p 驚きと感動を提供する Yoshida
  %aside
    %h3.sub-title カテゴリー
    %ul.sub-menu
      %li
        = link_to "" do
          Instagram
      %li
        = link_to "" do
          Facebook
      %li
        = link_to "" do
          Twitter
      %li
        = link_to new_project_path do
          Photo diary
    %h3.sub-title
      言語　
      language
    %p
      日本語　英語　中国語　　　対応いたします。
    %p Japanese,  English,  Chinese.


= render "partial/footer"

app/views/projects/contact.html.haml
#contact.big-bg
  = render "partial/header"
  .wrapper
    %h2.page-title Contact Me
    %form{action: "#"}
      %div
        %label{for: "name"} お名前 / NAME
        %input#name{name: "your-name", type: "text"}
      %div
        %label{for: "email"} メールアドレス / MAIL
        %input#email{name: "your-email", type: "text"}
      %div
        %label{for: "message"} メッセージ / MESSAGE
        %textarea#message{name: "your-message"}
      %input.button{type: "submit", value: "送信"}
= render "partial/footer"

app/views/projects/index.html.haml
#home.big-bg
  = render "partial/header"
  / home content
  .home-content.wrapper
    %h2.page-title Welcome to Yoshida
    %p.header-mini-text 写真をもっと楽しみたいあなたへ
    = link_to new_project_path, class: "button" do
      作品を見る

app/views/projects/new.html.haml
#phot.big-bg
  = render "partial/header"
  .phot-content.wrapper
    %h2.page-title Photo diary
    %p.header-mini-text 今まで撮影してきた人物、風景をお楽しみください
.slide
  .wrapper.grid.slider
    .item.big-box
      = image_tag "/assets/37677368.bce6c3dc34e149bdbce92fdd26c242f7.19041412.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9228.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9227.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9240.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9241.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9218.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9221.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9216.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9226.JPG"
      %p
    .item
      = image_tag  "/assets/IMG_9229.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9232.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9233.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9236.JPG"
      %p

  -# 上記スライドの内容の表示
  .wrapper.grid
    .item.big-box
      = image_tag "/assets/37677368.bce6c3dc34e149bdbce92fdd26c242f7.19041412.JPG"
    .item
      = image_tag "/assets/IMG_9228.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9227.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9240.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9241.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9218.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9221.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9216.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9226.JPG"
      %p

  .wrapper.grid
    .item.resize-phot
      = image_tag "/assets/37677211.8d624bc48a8345d29252138e76a56adc.19041412.JPG"
      %p
    .item.resize-phot
      = image_tag "/assets/IMG_5558.JPG"
      %p
    .item
      = image_tag "/assets/IMG_5459.JPG"
      %p
    .item
      = image_tag "/assets/IMG_6806.jpg"
      %p
    .item
      = image_tag "/assets/IMG_6929.jpg"
      %p
    .item
      = image_tag "/assets/IMG_8489.jpg"
      %p
    .item
      = image_tag "/assets/IMG_8540.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9235.JPG"
      %p
    .item
      = image_tag  "/assets/IMG_9229.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9232.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9233.JPG"
      %p
    .item
      = image_tag "/assets/IMG_9236.JPG"
      %p

= render "partial/footer"